final Map<String, Map<String, String>> wordCategoriesAr = {
  // المستوى 1
  'سامر':      {'category': 'أشخاص', 'description': 'اسم ولد في القصة.'},
  'سلحفاة':    {'category': 'حيوانات', 'description': 'حيوان يمشي ببطء في القصة.'},
  'أرنب':      {'category': 'حيوانات', 'description': 'حيوان صغير يركض بسرعة.'},
  'شجرة':      {'category': 'أشياء',   'description': 'نبات كبير له جذع وفروع.'},
  'غابة':      {'category': 'أماكن',   'description': 'مكان فيه أشجار وحيوانات كثيرة.'},
  'بيت':       {'category': 'أماكن',   'description': 'مكان نعيش فيه.'},
  'الحيوانات': {'category': 'حيوانات', 'description': 'كل الكائنات غير الإنسان.'},
  'الكل':      {'category': 'أشخاص',   'description': 'جميع الأشخاص أو الحيوانات.'},
  'الشكل':     {'category': 'مفاهيم',  'description': 'كيف يبدو الشيء.'},
  'كلام':      {'category': 'مفاهيم',  'description': 'ما نقوله للآخرين.'},
  'مساعدة':    {'category': 'مفاهيم',  'description': 'تقديم يد العون للآخرين.'},
  'خائف':      {'category': 'صفات',    'description': 'يشعر بالخوف.'},
  'يبكي':      {'category': 'أفعال',   'description': 'يذرف الدموع.'},
  'ابتسمت':    {'category': 'أفعال',   'description': 'ضحكت أو ظهرت عليها السعادة.'},
  'سارت':      {'category': 'أفعال',   'description': 'مشت أو تحركت للأمام.'},
  'ركض':       {'category': 'أفعال',   'description': 'جري بسرعة.'},
  'ضاعت':      {'category': 'أفعال',   'description': 'لم تعد تعرف الطريق.'},
  'طيبة':      {'category': 'صفات',    'description': 'لطيفة وتحب المساعدة.'},
  'حكيمة':     {'category': 'صفات',    'description': 'تفكر جيدًا وتتصرف بحكمة.'},
  'بطيئة':     {'category': 'صفات',    'description': 'تمشي ببطء ولا تستعجل.'},
  'ذكية':      {'category': 'صفات',    'description': 'تفكر بسرعة وتفهم الأمور.'},

  // المستوى 2
  'عمر':       {'category': 'أشخاص',   'description': 'اسم ولد وهو بطل القصة.'},
  'إياد':      {'category': 'أشخاص',   'description': 'اسم ولد جديد أصبح صديق عمر.'},
  'عائلته':    {'category': 'أشخاص',   'description': 'الناس الذين يعيش معهم عمر في البيت.'},
  'زملاءه':    {'category': 'أشخاص',   'description': 'الأطفال الآخرون في صف عمر.'},
  'طفل':       {'category': 'أشخاص',   'description': 'ولد صغير أو بنت صغيرة.'},
  'مدرسة':     {'category': 'أماكن',   'description': 'مكان يتعلم فيه الأطفال.'},
  'مدينة':     {'category': 'أماكن',   'description': 'مكان كبير فيه بيوت ومدارس.'},
  'المقعد':    {'category': 'أشياء',   'description': 'كرسي للجلوس في الصف.'},
  'رسمة':      {'category': 'أشياء',   'description': 'صورة يرسمها الطفل.'},
  'السيارات':  {'category': 'أشياء',   'description': 'مركبات تسير في الشارع.'},
  'الخجل':     {'category': 'مشاعر',   'description': 'شعور يجعلك هادئًا ولا تريد التحدث كثيرًا.'},
  'الحزن':     {'category': 'مشاعر',   'description': 'شعور بالحزن أو الانزعاج.'},
  'الراحة':    {'category': 'مشاعر',   'description': 'شعور جميل عندما يكون كل شيء جيد.'},
  'وحده':      {'category': 'مشاعر',   'description': 'شعور أنك وحدك بدون أصدقاء.'},
  'سعيد':      {'category': 'صفات',    'description': 'شخص يشعر بالفرح.'},
  'مبتسمًا':   {'category': 'صفات',    'description': 'شخص يظهر عليه الفرح.'},
  'جلس':       {'category': 'أفعال',   'description': 'عندما يجلس الشخص.'},
  'راقب':      {'category': 'أفعال',   'description': 'ينظر بهدوء إلى شيء.'},
  'ضحك':       {'category': 'أفعال',   'description': 'يصدر صوتاً من الفم عند السعادة.'},
  'رسم':       {'category': 'أفعال',   'description': 'يصنع صورة بالقلم أو الألوان.'},
  'قال':       {'category': 'أفعال',   'description': 'تحدث أو نطق بكلمات.'},
  'رد':        {'category': 'أفعال',   'description': 'أجاب على سؤال.'},
  'اقترب':     {'category': 'أفعال',   'description': 'مشى ليكون قريباً.'},
  'شعر':       {'category': 'أفعال',   'description': 'حسّ أو عرف شيئاً.'},
  'أصبح':      {'category': 'أفعال',   'description': 'تغير من حالة إلى أخرى.'},
  'شاركا':     {'category': 'أفعال',   'description': 'فعلا شيئًا معًا.'},
  'فازا':      {'category': 'أفعال',   'description': 'ربحا في مسابقة أو لعبة.'},
  'انتقل':     {'category': 'أفعال',   'description': 'ذهب إلى مكان جديد.'},
  'صداقتنا':   {'category': 'مفاهيم',  'description': 'العلاقة الجميلة بين الأصدقاء.'},
  'مسابقة':    {'category': 'مفاهيم',  'description': 'تحدي لمعرفة الفائز.'},

  // المستوى 3
  'المعلمة':   {'category': 'أشخاص',   'description': 'التي تدرّس الطلاب.'},
  'الطالب':    {'category': 'أشخاص',   'description': 'ولد يدرس في المدرسة.'},
  'زملائه':    {'category': 'أشخاص',   'description': 'طلاب آخرون في الصف.'},
  'المنزل':    {'category': 'أماكن',   'description': 'بيت سامر.'},
  'العشاء':    {'category': 'أشياء',   'description': 'وجبة طعام في المساء.'},
  'ورقة':      {'category': 'أشياء',   'description': 'صفحة يُكتب عليها.'},
  'القراءة':   {'category': 'مفاهيم',  'description': 'فعل قراءة الكتب.'},
  'العلوم':    {'category': 'مفاهيم',  'description': 'موضوع دراسي.'},
  'الرياضيات': {'category': 'مفاهيم',  'description': 'موضوع الأعداد.'},
  'الامتحان':  {'category': 'مفاهيم',  'description': 'اختبار في المدرسة.'},
  'الأمانة':   {'category': 'مفاهيم',  'description': 'قول الحقيقة وعدم الغش.'},
  'الصدق':     {'category': 'مفاهيم',  'description': 'قول الحقيقة دائماً.'},
  'الاحترام':  {'category': 'مفاهيم',  'description': 'معاملة الآخرين بلطف.'},
  'الارتباك':  {'category': 'مشاعر',   'description': 'شعور بالحيرة أو عدم الراحة.'},
  'القلق':     {'category': 'مشاعر',   'description': 'شعور بالخوف أو التوتر.'},
  'الخوف':     {'category': 'مشاعر',   'description': 'شعور بالخوف من أمر ما.'},
  'الفخر':     {'category': 'مشاعر',   'description': 'شعور بالسعادة لتحقيق شيء.'},
  'شجاعًا':    {'category': 'صفات',    'description': 'يتصرف بدون خوف.'},
  'ذكيًا':     {'category': 'صفات',    'description': 'يفكر جيداً ويتعلم بسرعة.'},
  'صامتًا':    {'category': 'صفات',    'description': 'لا يتكلم كثيراً.'},
  'يحاول':     {'category': 'أفعال',   'description': 'يجرب أن يفعل شيئًا.'},
  'يغش':       {'category': 'أفعال',   'description': 'لا يلتزم بالقواعد أو يغش بالامتحان.'},
  'رأى':       {'category': 'أفعال',   'description': 'نظر أو شاهد.'},
  'عاد':       {'category': 'أفعال',   'description': 'رجع إلى مكانه.'},
  'فكر':       {'category': 'أفعال',   'description': 'أخذ وقتًا للتفكير.'},
  'يخبر':      {'category': 'أفعال',   'description': 'يقول خبر لشخص.'},
  'يصمت':      {'category': 'أفعال',   'description': 'لا يتكلم.'},
  'بقي':       {'category': 'أفعال',   'description': 'استمر في وضع معين.'},
  'قالت':      {'category': 'أفعال',   'description': 'تكلمت أو أخبرت.'},
  'أثنت':      {'category': 'أفعال',   'description': 'مدحت وشكرت.'},
  'اختار':     {'category': 'أفعال',   'description': 'قرر ماذا يفعل.'},
  'نال':       {'category': 'أفعال',   'description': 'حصل على شيء.'},
  'تحدثت':     {'category': 'أفعال',   'description': 'تكلمت أو شرحت.'},
  'شرحَت':     {'category': 'أفعال',   'description': 'وضحت معنى شيء.'},
};
